Copy/paste and formatting nit fixes on artifactType strings
oras-project/artifacts-spec pull request #11
Opened 2021-08-13 21:56 UTC by SteveLasker

Cleans up some of the inconsistencies in artifactType strings from the original PR. 

Signed-off-by: Steve Lasker <stevenlasker@hotmail.com>

2021-08-16 23:06 UTC, michaelb990 requested changes
Just a few comments. Thanks for following up with this.

2021-08-16 23:06 UTC, michaelb990 commented on manifest-referrers-api.md
> +Artifact references are defined in the [artifact.manifest spec][oras.artifact.manifest-spec] through the [`subjectManifest`][oras.artifact.manifest-spec-manifests] property.
why is it `artifact.manifest` here but `artifact-manifest` in the paragraph above? I'm not sure what syntax this is using, but we should try to be consistent. FWIW, I prefer `artifact-manifest`.

2021-08-16 23:06 UTC, michaelb990 commented on manifest-referrers-api.md
> +[distribution-spec][oci-distribution-spec] implementations MAY implement `artifactType` filtering. Some artifacts types including Notary v2 signatures, may return multiple signatures of the same `art
I'd prefer wrapping to a given character limit (as it was originally) or putting each sentence on a new line. This makes changes significantly easier to review and is consistent with how the OCI specs are formatted (see [distribution-spec here](https://raw.githubusercontent.com/opencontainers/distribution-spec/main/spec.md))

2021-08-16 23:06 UTC, michaelb990 commented on manifest-referrers-api.md
> +While this will cause additional round trips, manifests are typically small in comparison to the full pull time for a manifest and its blobs or layers. In the future, responses could be extended to i
same here.

2021-08-16 23:14 UTC, sajayantony commented on descriptor.md
> +  "artifactType": "org.cncf.notary.v2"
Does this mean that we will be using `org.cncf.notary.v2` for artifact types and do we have similar guidance for other projects?

2021-08-16 23:16 UTC, sajayantony commented on scenarios.md
> +    "artifactType": "cncf.notary.v2",
Should this also be `org.cncf.notary.v2`

2021-08-16 23:17 UTC, sajayantony commented on scenarios.md
>  - [oras.artifact.manifest spec][artifact-manifest-spec] for more info on the manifest
`artifact-manifest` . I believe the -spec has been removed.

2021-08-16 23:19 UTC, sajayantony requested changes
Some minor NITs and also consistency for artifactType values.

2021-08-16 23:19 UTC, sajayantony commented on artifact-manifest/net-monitor-image-signature.json
> +  "artifactType": "cncf.notary.v2",
`org.cncf.notary.v2` ?

2021-08-16 23:29 UTC, SteveLasker commented on manifest-referrers-api.md
> +[distribution-spec][oci-distribution-spec] implementations MAY implement `artifactType` filtering. Some artifacts types including Notary v2 signatures, may return multiple signatures of the same `art
There are multiple sections that use the paragraph formatting of one continuous line. Are you asking for all of these to be changed? Github comparisons show these changes pretty well, and I'm worried how tooling might convert markdown with multiple lines into a paragraph.

2021-08-16 23:30 UTC, SteveLasker commented on manifest-referrers-api.md
> +While this will cause additional round trips, manifests are typically small in comparison to the full pull time for a manifest and its blobs or layers. In the future, responses could be extended to i
I've changed these two references to have their sentences on different lines. If we really want to write all specs this way, we should likely add some contributor guidance.

2021-08-16 23:31 UTC, SteveLasker commented on descriptor.md
> +  "artifactType": "org.cncf.notary.v2"
I've created an [issue to track the guidance on `artifactType`](https://github.com/oras-project/artifacts-spec/issues/8). While we need to finalize this before tooling starts generating `artifactTypes` that we'll persist, we don't need to block implementing the APIs.

2021-08-16 23:33 UTC, SteveLasker commented on scenarios.md
>  - [oras.artifact.manifest spec][artifact-manifest-spec] for more info on the manifest
I've changed, per Michaels feedback above.

2021-08-16 23:36 UTC, SteveLasker commented on manifest-referrers-api.md
> +Artifact references are defined in the [artifact.manifest spec][oras.artifact.manifest-spec] through the [`subjectManifest`][oras.artifact.manifest-spec-manifests] property.
The first sentence of the doc (line 3) refers to the artifacts spec as a concept. The subsequent references refer to the implementation, and/or the actual document. 
Since the document is called `artifacts-manifest.md`, I shortened it to artifacts-manifest. 
When referring to the mediaType, I use the fully qualified. notation.

Not sure if this is the best answer, but that was the thought. I did fix a few references to be more consistent.

2021-08-16 23:54 UTC, michaelb990 commented on manifest-referrers-api.md
> +[distribution-spec][oci-distribution-spec] implementations MAY implement `artifactType` filtering. Some artifacts types including Notary v2 signatures, may return multiple signatures of the same `art
I would love for them all to be changed! It's fine if we don't go through and do this immediately, but I'd at least like to agree on the direction so we don't make it *worse*.

Any tooling that supports markdown should convert markdown with multiple lines into a paragraph.

https://daringfireball.net/projects/markdown/syntax#p

2021-08-16 23:58 UTC, michaelb990 commented on manifest-referrers-api.md
> +Artifact references are defined in the [artifact.manifest spec][oras.artifact.manifest-spec] through the [`subjectManifest`][oras.artifact.manifest-spec-manifests] property.
I'm not sure I'm seeing the difference between the "concept" of the `artifact-manifest` and the "implementation" of the `artifact.manifest`. I think they should both be called `artifact-manifest`.

I am not suggesting any changes to usages of the fully qualified mediaType.

2021-08-16 23:59 UTC, SteveLasker commented on manifest-referrers-api.md
> +While this will cause additional round trips, manifests are typically small in comparison to the full pull time for a manifest and its blobs or layers. In the future, responses could be extended to i
Fair enough. Sajay reminded me that not all tooling supports rich text formatting and visualizations like github, so I've made the edits to this PR.

This would be a great to have something added to https://github.com/oras-project/community for contributing.

2021-08-17 00:00 UTC, michaelb990 approved these changes
LGTM

2021-08-17 00:19 UTC, sajayantony approved these changes

2021-08-17 00:36 UTC, merged