referrers api: add pagination details
oras-project/artifacts-spec pull request #16
Opened 2021-08-17 07:42 UTC by aviral26

This PR add details around `/referrers` API pagination.

2021-08-17 21:53 UTC, mnltejaswini commented on manifest-referrers-api.md
> +Paginated results are obtained by adding a `n` parameter to the request URL, indicating that the response should be
Do you want to mention the default value if not given?

2021-08-18 03:03 UTC, aviral26 commented on manifest-referrers-api.md
> +Paginated results are obtained by adding a `n` parameter to the request URL, indicating that the response should be
This is mentioned on line 22. Let me move that here.

2021-08-18 16:11 UTC, sajayantony approved these changes
LGTM. 

At this point I believe we have good confidence that it doesn't diverge from the registry implementations. 
If there are additions we can revisit this with an issue.

2021-08-18 17:16 UTC, michaelb990 requested changes
Couple small comments. Thanks for putting this together!

2021-08-18 17:16 UTC, michaelb990 commented on manifest-referrers-api.md
> +The `/referrers` API MUST provide for paging.
Should we change this to "registries MUST set a default value" even if we're not prescribing what the value should be?

2021-08-18 17:16 UTC, michaelb990 commented on manifest-referrers-api.md
> +limited to `n` results. The default page size SHOULD be set to 10. Starting a paginated flow begins as:
If the `n` value isn't present in the request URL, paginated results are still returned, right?

I'd suggest changing this to:
```suggestion
The `/referrers` API returns a paginated list of descriptors. Page size can be specified by adding a `n` parameter to the request URL, indicating that the response should be
limited to `n` results. The default page size SHOULD be set to 10. Starting a paginated flow begins as:
```

2021-08-18 17:19 UTC, michaelb990 commented on manifest-referrers-api.md
> +limited to `n` results. The default page size SHOULD be set to 10. Starting a paginated flow begins as:
Also, I'm realizing that you moved the default page size statement down here. I'm fine with suggesting a default, but I still think that we should include a requirement that registries MUST have a default so clients know whether they need to always pass the `n` query param or not.

2021-08-18 17:40 UTC, jonjohnsonjr commented on manifest-referrers-api.md
> +limited to `n` results. The default page size SHOULD be set to 10. Starting a paginated flow begins as:
> I still think that we should include a requirement that registries MUST have a default

In the [original spec](https://docs.docker.com/registry/spec/api/#catalog):

> `n` | query | Limit the number of entries in each response. It not present, all entries will be returned.

2021-08-18 21:21 UTC, sajayantony commented on manifest-referrers-api.md
> +limited to `n` results. The default page size SHOULD be set to 10. Starting a paginated flow begins as:
Having a limit here rather than an unbounded response makes sense to me. Unbounded tag listing or repository listing can be a challenge when we have a large number of repositories or tags. 

If we specify that if `n` is not present,  clients can expect the full response,  then a client might just never follow and assume that received the full set and this can be bad for any kind of backup scenario. 

Should we clarify the expectation here - 

1. If `n` is not provided the server `MAY` return a default number of references.
  _Default item counts may be implementation specific and maybe we can add recommendations as an another issue_ 

1. If the count `n` is specified the server `MAY` return up to `n`. 
  _This would leave the implementation up to the service to decide how many they want to return which can be limited by things like number of items or response size._ 

1. Clients are expected for follow the `Link` header since the server might have more data
_In some implementations looking into multiple partitions returns empty sets and so non-presence of items should not be considered as lack of more data is the point I am trying to emphasize here_

Does this guidance sound like its diverging from the the original pagination API (ignoring the lexical ordering issue) but ensure that we fill in the gaps for client authors?

2021-08-18 21:28 UTC, jonjohnsonjr commented on manifest-referrers-api.md
> +limited to `n` results. The default page size SHOULD be set to 10. Starting a paginated flow begins as:
I view the absence of `n` as a request for all entries, and registries MAY enforce some limit, so your clarification of expectations seems good to me.

2021-08-19 01:57 UTC, mnltejaswini commented on manifest-referrers-api.md
> +limited to `n` results. The default page size SHOULD be set to 10. Starting a paginated flow begins as:
@sajayantony  your guidance looks good. 
3rd point emphasizes that Clients are expected to follow Link header **if present** irrespective of whether there are response items or not. 

Is there a need to mention the default value in the spec ```The default page size SHOULD be set to 10.```
or can it focus on the requirement that, registry servers MAY enforce limits irrespective of  whether page size is given or not.

2021-08-19 06:36 UTC, aviral26 commented on manifest-referrers-api.md
> +limited to `n` results. The default page size SHOULD be set to 10. Starting a paginated flow begins as:
I've included these points in the latest revision, as well as clarified that specifying a page size is optional for clients. Is there a suggestion around a RECOMMENDED default page size? I'm okay leaving this unspecified.

2021-08-19 06:43 UTC, aviral26 commented on manifest-referrers-api.md
> +The `/referrers` API MUST provide for paging.
This is subsumed by the discussion below.

2021-08-19 22:35 UTC, sajayantony commented on manifest-referrers-api.md
> +limited to `n` results. The default page size SHOULD be set to 10. Starting a paginated flow begins as:
From the past conversation for MAX and SIZE recommendations in the other groups, this need not be something that this PR needs to address is my opinion. Currently I feel that the spec provides enough guidance for clients to implement and we can revisit this with actual test or real world limits with data backing the recommendation or at least a reference implementation.

2021-08-19 23:06 UTC, mnltejaswini commented on manifest-referrers-api.md
> +limited to `n` results. The default page size SHOULD be set to 10. Starting a paginated flow begins as:
I am fine with not mentioning any specific default size in this spec.

2021-08-19 23:17 UTC, mnltejaswini commented on manifest-referrers-api.md
> +encoded in a RFC5988 `Link` header, as a "next" relation. Clients SHOULD treat this as an opaque value and not try to
do you want to phrase as MUST treat this as an opaque value ?

2021-08-19 23:18 UTC, mnltejaswini commented
LGTM

2021-08-20 04:18 UTC, aviral26 commented on manifest-referrers-api.md
> +encoded in a RFC5988 `Link` header, as a "next" relation. Clients SHOULD treat this as an opaque value and not try to
Once a client has the `Link` value, they can do whatever they want with it. I think we can only recommend here rather than have it as a requirement.

2021-08-20 22:21 UTC, SteveLasker approved these changes
LGTM

2021-08-20 22:22 UTC, merged