add go specs for artifact manifest
oras-project/artifacts-spec pull request #17
Opened 2021-08-17 11:57 UTC by aviral26

This PR adds Go specs for ORAS Artifact manifest. Addresses #15.

2021-08-17 15:50 UTC, sajayantony approved these changes

2021-08-17 15:50 UTC, sajayantony commented on specs-go/v1/mediatype.go
> +	MediaTypeArtifactManifest = "application/vnd.oras.artifact.manifest.v1+json"
We can revisit this once we have the MediaType finalized as a part of the #14

2021-08-18 23:00 UTC, SteveLasker requested changes
LGTM with the minor, but important change on the MediaTypeArtifactManifest

2021-08-18 23:00 UTC, SteveLasker commented on specs-go/v1/mediatype.go
> +	MediaTypeArtifactManifest = "application/vnd.oras.artifact.manifest.v1+json"
> "application/vnd.oras.artifact.manifest.v1+json"

`application/vnd.cncf.oras.artifact.manifest.v1+json`

2021-08-18 23:07 UTC, sajayantony commented on specs-go/v1/mediatype.go
> +	MediaTypeArtifactManifest = "application/vnd.oras.artifact.manifest.v1+json"
@SteveLasker - Shall we fix this as a part of #14 since is just moving the media types from previous OCI repositories?

2021-08-18 23:12 UTC, SteveLasker commented on specs-go/v1/mediatype.go
> +	MediaTypeArtifactManifest = "application/vnd.oras.artifact.manifest.v1+json"
The other is about the artifactType, and whether is should follow jana conventions. This one just need cncf to be consistent with the apec

2021-08-19 06:54 UTC, aviral26 commented on specs-go/v1/mediatype.go
> +	MediaTypeArtifactManifest = "application/vnd.oras.artifact.manifest.v1+json"
Updated.

2021-08-19 16:23 UTC, SteveLasker reviewed
Some additional questions on why we need dependencies to the image-spec

2021-08-19 16:23 UTC, SteveLasker commented on go.mod
> +require github.com/opencontainers/image-spec v1.0.1
Where do we have a dependency on the image-spec? 
A significant goal of the artifacts-spec is to decouple the interdependencies between the distribution-spec and any specific artifact type (like the container image-spec). See [Proposal: Decoupling Registries from Specific Artifact Specs](https://hackmd.io/iOemxuZaT8O5WciRLm0K9g)

2021-08-19 16:23 UTC, SteveLasker commented on go.sum
> +github.com/opencontainers/image-spec v1.0.1 h1:JMemWkRwHx4Zj+fVxWoMCFm/8sYGGrUVojFA6h/TRcI=
Same comment as above:

> Where do we have a dependency on the image-spec?

2021-08-19 16:23 UTC, SteveLasker commented on specs-go/v1/manifest.go
> +import v1 "github.com/opencontainers/image-spec/specs-go/v1"
where/;why?

2021-08-19 16:31 UTC, sajayantony commented on specs-go/v1/manifest.go
> +import v1 "github.com/opencontainers/image-spec/specs-go/v1"
Artifact-spec doesn’t need to redefine the standard descriptor 
SubjectManifest v1.Descriptor `json:"subjectManifest"`

2021-08-19 16:44 UTC, SteveLasker commented on specs-go/v1/manifest.go
> +import v1 "github.com/opencontainers/image-spec/specs-go/v1"
Actually, this is the purpose fo the artifact-descriptor as it adds the `artifactType` property, and is a superset of the image-spec-descriptor.

2021-08-19 17:51 UTC, sajayantony commented on specs-go/v1/manifest.go
> +import v1 "github.com/opencontainers/image-spec/specs-go/v1"
I would ideally not like to redefine structures that have already been well defined in other locations in projects we typically are comfortable taking dependency on.  After discussions with @SteveLasker I think its important to call out this specific case which is that these are only spec files and `image-spec` repo is a subset of OCI which is more about container images (or process containers) and there is no reason for client library which wants to deal with signatures need to bring in `image-spec` into its modules as an indirect dependency. 

The descriptor if at all there was should come from distribution-spec but since that is also not solidified and is under a different body (OCI) it is ok to just use the artifactDescriptor for both blobs and subjectManifest since the annotation fields are optional and anyone building clients don't have indirect deps on `image-spec`

2021-08-19 18:10 UTC, jonjohnsonjr commented on specs-go/v1/manifest.go
> +import v1 "github.com/opencontainers/image-spec/specs-go/v1"
> and is a superset of the image-spec-descriptor.

If it's intended to be a superset of the image-spec descriptor, you have a logical dependency on image-spec. If you're intending to fork the image-spec descriptor, that's fine, but it's not really a superset anymore if they can diverge.

2021-08-19 18:23 UTC, SteveLasker commented on specs-go/v1/manifest.go
> +import v1 "github.com/opencontainers/image-spec/specs-go/v1"
> but it's not really a superset anymore if they can diverge.

That's fair. It's a superset of what's defined in the 1.0 of the image-spec. Having it defined in the artifacts-spec, or preferably in the distribution-spec would be to allow the image-spec maintainers to evolve the image-spec as they want without destabilizing artifacts-manifest consumers.

2021-08-20 04:05 UTC, aviral26 commented on specs-go/v1/manifest.go
> +import v1 "github.com/opencontainers/image-spec/specs-go/v1"
So as artifact descriptors, `blobs` and `subjectManifest` properties will not support `annotations`?

2021-08-20 07:40 UTC, aviral26 commented on go.mod
> +require github.com/opencontainers/image-spec v1.0.1
See discussion in `manifest.go`

2021-08-20 07:41 UTC, aviral26 commented on go.sum
> +github.com/opencontainers/image-spec v1.0.1 h1:JMemWkRwHx4Zj+fVxWoMCFm/8sYGGrUVojFA6h/TRcI=
See discussion in manifest.go

2021-08-20 07:41 UTC, aviral26 commented on specs-go/v1/manifest.go
> +import v1 "github.com/opencontainers/image-spec/specs-go/v1"
Please see #21

2021-08-20 09:26 UTC, aviral26 commented on specs-go/v1/manifest.go
> +import v1 "github.com/opencontainers/image-spec/specs-go/v1"
Removed the dependency on image-spec.

2021-08-20 16:12 UTC, SteveLasker approved these changes
LGTM

2021-08-20 16:13 UTC, merged