Release names and release criteria
oras-project/artifacts-spec pull request #19
Opened 2021-08-18 20:49 UTC by SteveLasker

Adds names of releases, and sets a triage bar for what can be changed within a draft, a release candidate, vs. a major and minor release.

Signed-off-by: Steve Lasker <stevenlasker@hotmail.com>

2021-08-19 20:19 UTC, sajayantony commented
Looking at other CNCF projects, listed below - I see for releasing binaries and images/artifacts `alpha` makes sense to me. Draft of a specification is what I can relate with in my earlier life. 

https://github.com/istio/enhancements/issues/12
https://registry.terraform.io/providers/hashicorp/kubernetes-alpha/latest
https://github.com/open-policy-agent/gatekeeper/blob/master/charts/gatekeeper/README.md
https://www.cncf.io/blog/2017/04/24/release-update-prometheus-1-6-1-sneak-peak-2-0/

/cc @lachie83 for inputs on this since we want to start releasing oras and a version of distribution that supports reference-types.

2021-08-20 18:36 UTC, sajayantony commented on release-criteria.md
> +1. Additional properties that may leak expectations a server may be processing the property.
This is mixing release criteria with Governance and needs to be split.

2021-08-20 22:23 UTC, SteveLasker commented on release-criteria.md
> +1. Additional properties that may leak expectations a server may be processing the property.
Can you elaborate on why this is governance? 
This is setting a bar for what types of changes would be accepted, as a bar. The maintainers can agree, through super majority to just about anything. So, is this in conflict, or simply providing structure to work within?

2021-08-20 22:33 UTC, jonjohnsonjr commented on release-criteria.md
> +1. Additional properties that may leak expectations a server may be processing the property.
I'm having a hard time understanding what this sentence means, myself.

2021-08-21 00:59 UTC, sajayantony commented on release-criteria.md
> +1. Additional properties that may leak expectations a server may be processing the property.
I'm trying to understand what is the scope of the PR and why we are defining a PR acceptance criteria in the release guidance. 
Pull request guidelines should be a contributing guideline and scope is open to discussion as long as it is as per CNCF code of conduct. For e.g. - https://github.com/helm/helm/blob/main/CONTRIBUTING.md

2021-08-23 17:25 UTC, sajayantony commented on release-criteria.md
> +1. Additional properties that may leak expectations a server may be processing the property.
@lachie83  - pointed me to this one as well - https://github.com/cnabio/cnab-spec/blob/main/901-process.md

2021-08-26 19:23 UTC, michaelb990 requested changes

2021-08-26 19:23 UTC, michaelb990 commented on release-criteria.md
> +Content persisted with these versions MUST use the `"mediaType": application/vnd.cncf.oras.artifact.manifest.1.0-draft[n].json` version to assure it's not assumed to be compliant with committed, rele
nit: you're mixing `"mediaType"` in quotes & `application/vnd.cncf.oras.artifact.manifest.1.0-draft[n].json` not quoted here. 

For OCI media types, we simply use `v1`. My understanding of this is that all you *should* have to know is the major version of the manifest in order to know whether or not you can parse it, as ANY additional changes to v1 manifests MUST be non-breaking. Will we make similar guarantees in ORAS? I think we should.

Also, the [standard way](https://en.wikipedia.org/wiki/Media_type) I've seen this written is to have the type/subtype of the media type and then a format suffix separated by a `+`. I'd propose changing the mediaType to:

`application/vnd.cncf.oras.artifact.manifest.v1-draft[n]+json`

2021-08-26 19:23 UTC, michaelb990 commented on release-criteria.md
> +1. Issues related to content copying within and across registry implementations
This one seems pretty specific, can we loosen it to be more generic? What about issues related to the content lifecycle? Annotations? Descriptors? 

Actually, what if we just removed this? Why do we need to say what is and isn't an acceptable issue? Is that something that we're following from other projects? From my POV, an issue is always acceptable, but whether we will merge a PR for it now or later is what we need guidance for.

2021-08-26 19:23 UTC, michaelb990 commented on release-criteria.md
> +2. Changes that may cause failures in retrieving artifact-manifest content, including the traversal of references.
What is the "traversal of references"? This isn't talked about in our spec so far. I believe the only operations we're supporting do single hop lookups, so is this necessary?

2021-08-26 19:23 UTC, michaelb990 commented on release-criteria.md
> +1. Additional properties that may leak expectations a server may be processing the property.
+1, I think this sentence is just missing some words. Can we rephrase it to be more clear?

2021-08-26 19:29 UTC, jonjohnsonjr commented on release-criteria.md
> +Content persisted with these versions MUST use the `"mediaType": application/vnd.cncf.oras.artifact.manifest.1.0-draft[n].json` version to assure it's not assumed to be compliant with committed, rele
+1

`+json` is part of the [structured syntax suffix registry](https://www.iana.org/assignments/media-type-structured-suffix/media-type-structured-suffix.xhtml).

2021-09-03 23:20 UTC, SteveLasker commented
Closing in lieu of #35

2021-09-03 23:20 UTC, closed without merging