Readme Updates
oras-project/artifacts-spec pull request #36
Opened 2021-09-03 00:25 UTC by SteveLasker

Cleaning up the readme, scenarios, manifest and referrers spec markdown files.

2021-09-03 18:56 UTC, michaelb990 requested changes
It was hard to follow some of this because there are formatting changes mixed with changes in the language. Left a few comments, tried to focus on the language changes.

2021-09-03 18:56 UTC, michaelb990 commented on scenarios.md
> +- Build atop the existing distribution-spec push, persist and pull APIs.
```suggestion
- Build atop the existing distribution-spec push and pull APIs.
```

nit: Push & persist APIs are equivalent in my mind.

2021-09-03 18:56 UTC, michaelb990 commented on scenarios.md
> +- Adding related artifacts, maintaining the original artifact digest and collection of associated tags.
Not sure I understand what the second part of this means.

2021-09-03 18:56 UTC, michaelb990 commented on scenarios.md
> +- Copying a graph of references within and across ORAS Artifact enabled, distribution spec based registries, enabling an image, its signatures, SBoMs and images with on-demand loading to be copied as
what does "on-demand loading" mean here? I'd suggest removing it and focusing on the ability to copy an image & its related artifacts between registries.

2021-09-03 18:56 UTC, michaelb990 commented on scenarios.md
> +Just as the layers of an OCI Image are deleted (*ref-counted -1*), any artifacts with a `subject` referring to the target manifest MAY be deleted (*ref-counted -1*).
In other parts of the spec, we've removed the words that imply a certain GC algorith like "ref-count". Should we do that here?

2021-09-03 18:56 UTC, michaelb990 commented on scenarios.md
> +### Flat Listings
Why are we adding this? I'm not sure it belongs in the spec.

2021-09-03 18:56 UTC, michaelb990 commented on scenarios.md
>  ![flat listing of ORAS Artifacts](media/repo-listing-attributed.svg)
alt-text should be changed here i think

2021-09-03 21:19 UTC, SteveLasker commented on scenarios.md
> +- Adding related artifacts, maintaining the original artifact digest and collection of associated tags.
One of the goals of the Artifacts Spec is the ability to add links to existing content. That's important as it doesn't break existing workflows that are based on the digest and/or tag of the original content.
If you push `net-monitor:v1` with a digest of `sha256:abc123`, and you have a helm chart that references it, you need that to be maintained.
If you add an SBoM or a signature, the helm chart shouldn't change it's digest or tag reference. 

Put that in a bullet :)

2021-09-03 21:22 UTC, SteveLasker commented on scenarios.md
> +- Copying a graph of references within and across ORAS Artifact enabled, distribution spec based registries, enabling an image, its signatures, SBoMs and images with on-demand loading to be copied as
it's a nod to the nydus folks that are also leveraging the Aritfact Manifest/Reference Types to support their scenario. 
See: [net-monitor-image-nydus-ondemand-loading.json](https://github.com/oras-project/artifacts-spec/blob/main/examples/net-monitor-image-nydus-ondemand-loading.json) for an example.

It looks like others that are also doing expansion will use this, like Alibabas DADI implementation.

2021-09-03 21:25 UTC, SteveLasker commented on scenarios.md
> +### Flat Listings
Which part are you asking about? The flat listing?

2021-09-03 23:28 UTC, michaelb990 approved these changes

2021-09-03 23:29 UTC, michaelb990 commented
Make sure to squash-merge or clean up commits before merging.

2021-09-06 13:25 UTC, justincormack approved these changes

2021-09-07 04:09 UTC, sajayantony approved these changes

2021-09-07 15:45 UTC, merged