Artifact type authoring
oras-project/artifacts-spec pull request #39
Opened 2021-09-08 17:40 UTC by SteveLasker

Address #8 by referencing existing OCI Artifact docs.

A more detailed option would be to pull in the [OCI Artifact Authors doc](https://github.com/opencontainers/artifacts/blob/master/artifact-authors.md), adjusting `manifest.config.mediaType` with `manifest.artifactType`.

I'd duggest we keep this more simplistic option for now, and we can add more details that don't impact the implementation of the spec at a later date.

2021-09-08 18:01 UTC, sajayantony commented on artifact-manifest.md
> +  Artifact authors that implement `oras.artifact.manifest` use `artifactType` to differentiate the type of artifact. example:(`application/x.example.sbom.v0` from `application/vnd.cncf.notary.v2`).
I think you should just point to the artifact manifest spec.

2021-09-08 18:15 UTC, sajayantony submitted a review, later dismissed

2021-09-09 20:58 UTC, michaelb990 requested changes
A couple questions, but otherwise looks good.

2021-09-09 20:58 UTC, michaelb990 commented on artifact-manifest.md
> +  This field contains the `mediaType` of this document, differentiating from [image-manifest][oci-image-manifest-spec] and [image-index][oci-image-index]. The `mediaType` for this manifest type MUST
How can artifact authors support multiple `mediaType` versions when there aren't more than one version in existence?

I'm trying to understand (as an "artifact author") what I should do with this requirement:
> Artifact authors SHOULD support multiple `mediaType` versions to provide the best user experience for their artifact type.

Does this mean that I SHOULD support both image, image index, and artifact manifests? Or that I SHOULD support the artifact manifest V1 AND a yet-to-be-invented artifact manifest V2?

2021-09-09 20:58 UTC, michaelb990 commented on artifact-manifest.md
> +  The `artifactType` is equivalent to `manifest.config.mediaType` in [OCI Artifacts][oci-artifacts].
Maybe something like this to make it clearer? It's the values of the field that we expect to the be the same.

```suggestion
  The `artifactType` values are equivalent to the values used in the `manifest.config.mediaType` in [OCI Artifacts][oci-artifacts].
```

2021-09-09 21:34 UTC, SteveLasker commented on artifact-manifest.md
> +  This field contains the `mediaType` of this document, differentiating from [image-manifest][oci-image-manifest-spec] and [image-index][oci-image-index]. The `mediaType` for this manifest type MUST
Thanks Michael,
This is about future-proofing, and setting expectations. When discussing changes to the image-spec, there was constant concern about breaking changes, and what should be put into the existing `image.manifest` mediaType, with `.v1`. If we were to add a new version to the image-spec, and change the version in the mediaType, all clients would break, or not know how to support it.
This sets the expectation that the version WILL change in the future, and developers SHOULD code for that scenario. 
That might mean, parse: `.v1` from `application/vnd.cncf.oras.artifact.manifest.v1+json`.
I do think we should add an artifact authors doc, similar to the OCI Artifacts doc that speaks to these details, but these are additive docs. Many who provided feedback said they read the code, before reading the specs. So, we'll likely show this in the [oras-go](https://github.com/oras-project/oras-go) libraries, and [distribution/distribution](https://github.com/distribution/distribution) at some point.

2021-09-09 21:37 UTC, SteveLasker commented on artifact-manifest.md
> +  The `artifactType` is equivalent to `manifest.config.mediaType` in [OCI Artifacts][oci-artifacts].
I'd use the [Commit suggestion] button, but I fear the dread of DCO errors. If someone knows "the trick", happy to hit the button, `git pull` and give appropriate credit.

2021-09-09 22:11 UTC, jonjohnsonjr commented
> This sets the expectation that the version WILL change in the future, and developers SHOULD code for that scenario.

What do we think that looks like in practice?

2021-09-09 22:27 UTC, SteveLasker commented
> What do we think that looks like in practice?

@jonjohnsonjr, please see #42

2021-09-09 23:07 UTC, michaelb990 commented on artifact-manifest.md
> +  This field contains the `mediaType` of this document, differentiating from [image-manifest][oci-image-manifest-spec] and [image-index][oci-image-index]. The `mediaType` for this manifest type MUST
Hmmm... This still has the issue I highlighted before. How can an artifact author support a version _which doesn't yet exist_?

The entire point of major versions is the understanding that they ARE breaking changes. No client, author, registry operator is able to commit to supporting version 2 of a manifest spec that hasn't been written yet. I think we should remove this sentence entirely -- my hope for this work is adoption into OCI before we release a version 2 so I'm not sure it makes sense to set ourselves up for multiple major versions to begin with.

2021-09-10 00:38 UTC, michaelb990 approved these changes

2021-09-10 01:04 UTC, sajayantony approved these changes

2021-09-10 01:12 UTC, merged