propose relative url for pagination next link
oras-project/artifacts-spec pull request #94
Opened 2022-03-31 18:29 UTC by northtyphoon

resolve #93 

Signed-off-by: Bin Du <bindu@microsoft.com>

2022-03-31 18:55 UTC, SteveLasker submitted a review, later dismissed
LGTM,
Thanks, @northtyphoon, this is a great example of iterating the spec as its being implemented, identifying gaps enabling real-world implementations.

2022-03-31 20:21 UTC, sajayantony requested changes

2022-03-31 20:21 UTC, sajayantony commented on manifest-referrers-api.md
> +```
We need to fix this example to - 

`/v2/hello-world/_oras/artifacts/referrers?digest=sha256:3c3a4604a545cdc127456d94e421cd355bca5b528f4a9c1905b15da2eb4a4c6b&n=5&nextToken=abc>; rel="next"`

Missing the /v2/{repo} base path

2022-04-01 00:14 UTC, sajayantony commented
@michaelb990 should we recommend only relative URLs?

2022-04-04 17:17 UTC, SteveLasker commented
@northtyphoon, can you fix your DCO issue on the "update example" commit?

2022-04-05 16:34 UTC, michaelb990 commented
> @michaelb990 should we recommend only relative URLs?

I would prefer to just have 1 way to do things where possible. Seems like the full URL doesn't work for some clients, and I don't see any downsides to just using the relative link. What do you think?

2022-04-05 18:27 UTC, SteveLasker commented
Fewer choices make things simpler. (👍)  @northtyphoon, can you update?

2022-04-06 00:10 UTC, sajayantony commented
+1 on making relative the only option.

2022-04-06 02:35 UTC, SteveLasker approved these changes
LGTM

2022-04-06 03:39 UTC, sajayantony approved these changes

2022-04-06 20:30 UTC, michaelb990 approved these changes

2022-04-06 20:31 UTC, merged